### PR TITLE
Add scrollEventThrottle to ignore warning of ScrollView, add custom scrollToTopAnimation option

### PR DESCRIPTION
**Pull request by xuho**

### CODE REVIEW

**Comment by ashrithks** [comment]
I will check and merge

**Comment by xuho** [comment]
> I will check and merge @xuho

thank u

**Comment by xuho** [comment]
@ashrithks: hi, have you checked my pull request?

**Comment by ashrithks** [comment]
Yes, can you add to readme as well,
scrollToTopAnimation

**Comment by xuho** [comment]
> Yes, can you add to readme as well,
> scrollToTopAnimation
Hi @ashrithks, I have added scrollToTopAnimation to README, please check this, thank.

**Comment by xuho** [comment]
@ashrithks in line 370 of index.js file.
```
contentContainerStyle={{ maxHeight: this.state.collapseHeight + (this.props.tabBarHeight ? this.props.tabBarHeight : 50) + this.state.contentHeight[this.state.currentPage] }}
```
You setup contentContainerStyle of scrollview, but when I setup tabs and don't know how many tab to render in runtime (number of tab is dynamic), this.state.contentHeight[this.state.currentPage] == undefined, so maxHeight is NaN and app will be crash. Please check and merge thi commit.
Thank so much.

**Comment by ashrithks** [comment]
Released version, 
https://www.npmjs.com/package/rn-collapsing-tab-bar/v/0.1.7

**Comment by xuho** [comment]
> Released version,
> https://www.npmjs.com/package/rn-collapsing-tab-bar/v/0.1.7
> @xuho

Thank so much 👍

**Pull request merged**
